export interface TrackingRow {
  _id: string;
  stage: string;
  status: string;
  cequenceId_Hashed?: string;
  cquenceDIN: string;
  cequenceId?: string;
  patientName: string;
  patientDOB: string;
  patientWeight: string;
  coicBagId: string;
  __v: number;
  pccNumber: string;
  totalVolume: string;
  productDose: string;
  marketAuthorizationNumber: string;
  nameAndAddress: string;
  productNDC: string;
  expirationDate: string;
  data_cart_order_id: string;
  associated_country: string;
  batch_id: string;
  created_at: string;
  updated_at: string;
  materialId: string;
  lastStatus: string;
  tentativeReleaseDate: string;
  materialNumber: string;
}
